import React, { useState, useEffect } from "react";
import { useAuth, apiFetch } from "./Auth";
import { searchTags, TagSelect } from "./Tags";

// High-performance client-side video thumbnail extractor
const extractVideoThumbnail = (videoFile) => {
  return new Promise((resolve, reject) => {
    const video = document.createElement('video');
    video.preload = 'auto';
    video.muted = true;
    video.playsInline = true;
    
    const videoUrl = URL.createObjectURL(videoFile);
    video.src = videoUrl;

    video.onloadeddata = () => {
      // Seek slightly past 0 to force decoding and avoid black frames
      video.currentTime = 0.2;
    };

    video.onseeked = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = video.videoWidth || 1280;
        canvas.height = video.videoHeight || 720;
        
        const ctx = canvas.getContext('2d');
        ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
        
        canvas.toBlob((blob) => {
          URL.revokeObjectURL(videoUrl);
          if (blob) {
            resolve(blob);
          } else {
            reject(new Error("Canvas blob generation failed."));
          }
        }, 'image/jpeg', 0.85); // 85% high-quality compression
      } catch (err) {
        URL.revokeObjectURL(videoUrl);
        reject(err);
      }
    };

    video.onerror = () => {
      URL.revokeObjectURL(videoUrl);
      reject(new Error("Failed to decode video file locally."));
    };
  });
};

const Upload = () => {
  const { user } = useAuth();
  const [files, setFiles] = useState([]);
  const [uploading, setUploading] = useState(false);
  const [progress, setProgress] = useState({});
  const [initialTag, setInitialTag] = useState("");

  useEffect(() => {
    const usernameLower = user?.username?.toLowerCase() || "lunepusa";
    const matchedTags = searchTags(usernameLower);
    const userTag = matchedTags.length > 0 ? matchedTags[0] : usernameLower;
    setInitialTag(userTag);
  }, [user]);

  const handleFileChange = (e) => {
    setFiles(Array.from(e.target.files));
  };

  const handleTagsSave = (tagsString) => {
    setInitialTag(tagsString);
  };

  const handleUpload = async () => {
    if (files.length === 0) return;

    setUploading(true);
    setProgress({});

    // Step 1: Tell backend about files to get presigned URLs
    const fileInfo = files.map((f) => ({
      name: f.name,
      type: f.type || "application/octet-stream",
    }));

    const res = await apiFetch("/presign", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ files: fileInfo }),
    });

    if (!res.ok) {
      const err = await res.text();
      alert("Failed to get upload URLs: " + err);
      setUploading(false);
      return;
    }

    const { presigned } = await res.json();

    // Step 2: Upload assets using your existing parallel tracking patterns
    const uploadPromises = presigned.map(async (item, i) => {
      const file = files[i];

      // Array to track companion upload operations (Video + Thumb)
      const operations = [];

      // Helper function wrapping XHR to maintain your current live % track metrics
     const uploadWithProgress = (targetUrl, payloadBlob, trackerKey) => {
        return new Promise((resolve, reject) => {
          const xhr = new XMLHttpRequest();
          xhr.open("PUT", targetUrl);

          xhr.upload.onprogress = (e) => {
            if (e.lengthComputable) {
              const percent = Math.round((e.loaded / e.total) * 100);
              setProgress((prev) => ({ ...prev, [trackerKey]: percent }));
            }
          };

          xhr.onload = () => (xhr.status === 200 ? resolve() : reject(new Error("Upload failed")));
          xhr.onerror = () => reject(new Error("Network error"));
          
          // Send the file payload raw without appending extra headers
          xhr.send(payloadBlob);
        });
      };
      // Extract and push video thumbnail if generated by backend
      if (file.type.startsWith("video/") && item.thumbPresignedUrl) {
        try {
          const thumbBlob = await extractVideoThumbnail(file);
          // Set a clear separate track layout for visibility
          const thumbTrackKey = `📸 Thumb: ${file.name}`;
          operations.push(uploadWithProgress(item.thumbPresignedUrl, thumbBlob, thumbTrackKey));
        } catch (thumbErr) {
          console.warn("Skipping thumbnail generation:", thumbErr.message);
        }
      }

      // Add main video/photo upload
      operations.push(uploadWithProgress(item.presignedUrl, file, file.name));

      // Wait for all chunks for this specific item to finalize
      await Promise.all(operations);

      // Step 3: Notify backend upload complete to save SQL row metadata
      await apiFetch("/upload-complete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          objectKey: item.objectKey,
          fileType: file.type,
          initialTag,
        }),
      });
    });

    try {
      await Promise.all(uploadPromises);
      alert("All content successfully pushed to R2!");
      setFiles([]);
      setProgress({});
    } catch (err) {
      alert("One or more uploads failed: " + err.message);
    } finally {
      setUploading(false);
    }
  };

  return (
    <div style={{ padding: "20px", textAlign: "center" }}>
      <h2>Upload New Content</h2>
      <input
        type="file"
        multiple
        onChange={handleFileChange}
        disabled={uploading}
        style={{ marginBottom: "10px" }}
      />
      <br />

      <div style={{ margin: "15px 0", textAlign: "left", maxWidth: "600px", marginLeft: "auto", marginRight: "auto" }}>
        <label style={{ display: "block", marginBottom: "8px", fontSize: "1em" }}>
          Tags for this upload:
        </label>
        <TagSelect
          initialTags={initialTag}
          onSave={handleTagsSave}
          placeholder="Type to add tags... (e.g. hidden, art, etc.)"
        />
      </div>

      <button
        onClick={handleUpload}
        disabled={uploading || files.length === 0}
        style={{ padding: "10px 20px", fontSize: "1em" }}
      >
        {uploading ? "Uploading..." : "Start Upload"}
      </button>

      {Object.keys(progress).length > 0 && (
        <div style={{ marginTop: "20px", textAlign: "left", maxWidth: "400px", margin: "20px auto" }}>
          <h3>Progress Tracker:</h3>
          {Object.entries(progress).map(([key, value]) => (
            <div key={key} style={{ margin: "4px 0", fontSize: "0.9em" }}>
              <strong>{key}</strong>: {value}%
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default Upload;